blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord Support
    url: https://discord.gg/V6FTB4u8ZH
    about: Get real-time help on our Discord server
  - name: ðŸ“– Documentation
    url: https://onze-plugins.gitbook.io/onze-plugins-docs/
    about: Check the wiki before opening an issue
